[package]
name = "rust_coroutines_rinha_2025"
version = "3.1.0"
edition = "2024"

[dependencies]
mimalloc = { version = "0.1", default-features = false }

tokio-uring = { git = "https://github.com/decathorpe/tokio-uring", rev = "025682b"}