[package]
name = "rust_coroutines_rinha_2025"
version = "1.0.4"
edition = "2024"

[dependencies]
num_cpus = "1.0"
smallvec = "1"
bytes = "1"

mimalloc = { version = "0.1", default-features = false }

may = { version = "0.3", default-features = false }
may_minihttp = { version = "0.1", default-features = false }
may_postgres = { git = "https://github.com/Xudong-Huang/may_postgres.git", rev = "917ed78", default-features = false, features = ["with-uuid-1"]}
serde_json = "1.0.140"
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"]}
ureq = { version = "3.0.12", features = ["json"] }
rust_decimal = { version = "1.37.2", features = ["serde-float", "db-postgres"] }
uuid = { version = "1.17.0", features = ["serde"] }

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'fat'
strip = true
debug = false
incremental = false
overflow-checks = false

[profile.release.package."*"]
opt-level = 3
codegen-units = 1
strip = true
debug = false
incremental = false
overflow-checks = false
