[package]
name = "rust_coroutines_rinha_2025"
version = "1.0.3"
edition = "2024"

[dependencies]
bytes = "1"
num_cpus = "1.0"
smallvec = "1.1"

log = { version = "0.4", features = ["release_max_level_off"] }
mimalloc = { version = "0.1", default-features = false }

may = { version = "0.3", default-features = false }
may_minihttp = { version = "0.1", default-features = false }
uuid = { version = "1.17.0", features = ["serde", "v4"] }
rust_decimal = { version = "1.37.2" }
chrono = "0.4.41"
ureq = "3.0.12"
serde = { version = "1.0.219", features = ["derive"] }
redis = "0.32.4"
itoa = "1.0.15"
once_cell = "1.21.3"
parking_lot = "0.12.4"
serde_json = "1.0.141"

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false
