[package]
name = "rust_coroutines_rinha_2025"
version = "1.0.4"
edition = "2024"

[dependencies]
bytes = "1"
num_cpus = "1.0"
smallvec = "1.1"

log = { version = "0.4", features = ["release_max_level_off"] }
mimalloc = { version = "0.1", default-features = false }

may = { version = "0.3", default-features = false }
may_minihttp = { version = "0.1", default-features = false }
may_postgres = { git = "https://github.com/Xudong-Huang/may_postgres.git", rev = "917ed78", default-features = false, features = [
    "with-uuid-1",
] }
uuid = { version = "1.17.0" }
rust_decimal = { version = "1.37.2", features = ["db-postgres"] }
chrono = "0.4.41"
ureq = "3.0.12"

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false
