services:
  haproxy:
    image: haproxy:3.2.3-alpine
    command: >
      sh -c "
      echo 'global
        maxconn 20000
      defaults
        mode http
        option http-keep-alive
        option srvtcpka
        option clitcpka
        option http-no-delay
        http-reuse aggressive
      frontend api_frontend
        bind *:80 alpn h2c
        default_backend api_backend
      backend api_backend
        balance static-rr
        server backend1 /sockets/may.sock.1
        server backend2 /sockets/may.sock.2' > /tmp/haproxy.cfg &&
      haproxy -f /tmp/haproxy.cfg"
    user: "0"
    ports:
      - "9999:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - backend
    volumes:
      - sockets:/sockets:rw
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.3"

  backend1:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.2
      SOCKET_PATH: /sockets/may.sock.1
    security_opt: 
          - seccomp=unconfined  # io_ring support
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: "0.6"

  backend2:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.1
      SOCKET_PATH: /sockets/may.sock.2
    volumes:
      - sockets:/sockets:rw
    security_opt: 
          - seccomp=unconfined  # io_ring support
    networks:
      - backend
      - payment-processor
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: "0.6"

volumes:
  sockets:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true