services:
  haproxy:
    image: haproxy:latest
    command: >
      sh -c "
      echo 'global
        maxconn 5000
      frontend api_frontend
        bind *:80
        default_backend api_backend
      backend api_backend
        balance static-rr
        server backend1 backend1:8080
        server backend2 backend2:8080
        default-server init-addr none' > /tmp/haproxy.cfg &&
      haproxy -f /tmp/haproxy.cfg"
    ports:
      - "9999:80"
    depends_on:
      - backend1
      - backend2
    logging:
      driver: "none"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          memory: 45M
          cpus: "0.2"

  backend1:
    build: .
    environment:
      PORT: 8080
      DEFAULT_PROCESSOR_URL: http://payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: http://payment-processor-fallback:8080
      REDIS_URL: redis://valkey
    depends_on:
      - valkey
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    command: >
      sh -c "
      ./rust_coroutines_rinha_2025
      --server
      --workers
      "
    deploy:
      resources:
        limits:
          memory: 110M
          cpus: "0.5"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend2:
    build: .
    environment:
      PORT: 8080
      DEFAULT_PROCESSOR_URL: http://payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: http://payment-processor-fallback:8080
      REDIS_URL: redis://valkey
    depends_on:
      - valkey
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    command: >
      sh -c "
      ./rust_coroutines_rinha_2025
      --server
      "
    deploy:
      resources:
        limits:
          memory: 110M
          cpus: "0.5"

  valkey:
    image: valkey/valkey:latest
    command: >
      valkey-server
      --save ""
      --appendonly no
      --io-threads 2
      --maxmemory 80mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 0
      --timeout 0
      --tcp-backlog 65535
      --databases 1
      --stop-writes-on-bgsave-error no
      --rdbcompression no
      --lazyfree-lazy-eviction yes
      --lazyfree-lazy-expire yes
      --lazyfree-lazy-server-del yes
      --replica-lazy-flush yes
    logging:
      driver: "none"
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 85M # valkey is using less than 15mb :/
          cpus: "0.3"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
