services:
  haproxy:
    image: haproxy:latest
    command: >
      sh -c "
      echo 'global
        maxconn 20000
      defaults
        mode http
        option http-keep-alive
        option srvtcpka
        option clitcpka
        option http-no-delay
        http-reuse aggressive
      frontend api_frontend
        bind *:80 alpn h2c
        default_backend api_backend
      backend api_backend
        balance static-rr
        server backend1 /sockets/may.sock.1
        server backend2 /sockets/may.sock.2' > /tmp/haproxy.cfg &&
      haproxy -f /tmp/haproxy.cfg"
    user: "0"
    ports:
      - "9999:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - backend
    volumes:
      - sockets:/sockets:rw
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.3"

  backend1:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.2
      SOCKET_PATH: /sockets/may.sock.1
      WORKER_SOCKET_PATH: /sockets/worker.sock
    security_opt: 
          - seccomp=unconfined  # io_ring support
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          memory: 10M
          cpus: "0.5"

  backend2:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.1
      SOCKET_PATH: /sockets/may.sock.2
      WORKER_SOCKET_PATH: /sockets/worker.sock
    volumes:
      - sockets:/sockets:rw
    security_opt: 
          - seccomp=unconfined  # io_ring support
    networks:
      - backend
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          memory: 10M
          cpus: "0.5"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      WORKER_SOCKET_PATH: /sockets/worker.sock
    security_opt: 
          - seccomp=unconfined  # io_ring support
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.2"

volumes:
  sockets:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true