services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:80"
    depends_on:
      - backend1
      - backend2
    logging:
      driver: "none"
    networks:
      - backend
      - payment-processor
    cpuset: "3-4"
    cap_add:
      - IPC_LOCK
      - SYS_NICE
    deploy:
      resources:
        limits:
          memory: 25M
          cpus: "0.2"

  backend1:
    build: .
    environment:
      PORT: 8080
      DEFAULT_PROCESSOR_URL: payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: payment-processor-fallback:8080
      REDIS_URL: redis://valkey
    depends_on:
      - valkey
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    command: >
      sh -c "
      ./rust_coroutines_rinha_2025
      --server
      --workers
      "
    cpuset: "0-1"
    cap_add:
      - IPC_LOCK
      - SYS_NICE
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.5"

  backend2:
    build: .
    environment:
      PORT: 8080
      DEFAULT_PROCESSOR_URL: payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: payment-processor-fallback:8080
      REDIS_URL: redis://valkey
    depends_on:
      - valkey
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    command: >
      sh -c "
      ./rust_coroutines_rinha_2025
      --server
      --workers
      "
    cpuset: "2-3"
    cap_add:
      - IPC_LOCK
      - SYS_NICE
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.5"

  valkey:
    image: valkey/valkey:latest
    command: >
      valkey-server
      --save ""
      --appendonly no
      --io-threads 2
      --maxmemory 20mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 0
      --timeout 0
      --tcp-backlog 65535
      --databases 1
      --stop-writes-on-bgsave-error no
      --rdbcompression no
      --lazyfree-lazy-eviction yes
      --lazyfree-lazy-expire yes
      --lazyfree-lazy-server-del yes
      --replica-lazy-flush yes
    logging:
      driver: "none"
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 25M # valkey is using less than 15mb when uncapped:o
          cpus: "0.3"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
