services:
  haproxy:
    image: haproxy:3.2.3-alpine
    command: >
      sh -c "
      echo 'global
        maxconn 20000
      defaults
        mode http
      frontend api_frontend
        bind *:80
        default_backend api_backend
      backend api_backend
        balance static-rr
        server backend1 /sockets/may.sock.1
        server backend2 /sockets/may.sock.2
        server backend3 /sockets/may.sock.3
        server backend4 /sockets/may.sock.4' > /tmp/haproxy.cfg &&
      haproxy -f /tmp/haproxy.cfg"
    user: "0"
    ports:
      - "9999:80"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
    networks:
      - backend
    volumes:
      - sockets:/sockets:rw
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.3"

  backend1:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.2
      PEER2_SOCKET: /sockets/may.sock.3
      PEER3_SOCKET: /sockets/may.sock.4
      SOCKET_PATH: /sockets/may.sock.1
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          memory: 75M
          cpus: "0.3"

  backend2:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.1
      PEER2_SOCKET: /sockets/may.sock.3
      PEER3_SOCKET: /sockets/may.sock.4
      SOCKET_PATH: /sockets/may.sock.2
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          memory: 75M
          cpus: "0.3"

  backend3:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.1
      PEER2_SOCKET: /sockets/may.sock.2
      PEER3_SOCKET: /sockets/may.sock.4
      SOCKET_PATH: /sockets/may.sock.3
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          memory: 75M
          cpus: "0.3"

  backend4:
    build: .
    environment:
      PEER1_SOCKET: /sockets/may.sock.1
      PEER2_SOCKET: /sockets/may.sock.2
      PEER3_SOCKET: /sockets/may.sock.3
      SOCKET_PATH: /sockets/may.sock.4
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          memory: 75M
          cpus: "0.3"

volumes:
  sockets:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true