services:
  haproxy:
    image: haproxy:latest
    command: >
      sh -c "
      echo 'global
        maxconn 5000
      frontend api_frontend
        bind *:80
        default_backend api_backend
      backend api_backend
        balance static-rr
        server backend1 backend1:8080
        server backend2 backend2:8080
        default-server init-addr none' > /tmp/haproxy.cfg &&
      haproxy -f /tmp/haproxy.cfg"
    ports:
      - "9999:80"
    depends_on:
      - backend1
      - backend2
    logging:
      driver: "none"
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 25M
          cpus: "0.2"

  backend1:
    build: .
    environment:
      PORT: 8080
      DEFAULT_PROCESSOR_URL: payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: payment-processor-fallback:8080
      PEER_HOST: backend2:8080
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    command: >
      sh -c "
      ./rust_coroutines_rinha_2025
      --server
      --workers
      "
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
      core:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 130M
          cpus: "0.65"

  backend2:
    build: .
    environment:
      PORT: 8080
      DEFAULT_PROCESSOR_URL: payment-processor-default:8080
      FALLBACK_PROCESSOR_URL: payment-processor-fallback:8080
      PEER_HOST: backend1:8080
    networks:
      - backend
      - payment-processor
    restart: unless-stopped
    command: >
      sh -c "
      ./rust_coroutines_rinha_2025
      --server
      --workers
      "
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
      core:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 130M
          cpus: "0.65"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true