[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-Z", "share-generics=y",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-Z", "share-generics=y",
]

# For all targets
[build]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-Z", "share-generics=y",
]