[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "target-cpu=skylake",
    "-C",
    "link-arg=-fuse-ld=lld",
    "-Z",
    "share-generics=y",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C",
    "target-cpu=skylake",
    "-C",
    "link-arg=-fuse-ld=mold",
    "-Z",
    "share-generics=y",
]

# For all targets
[build]
rustflags = [
    "-C",
    "target-cpu=skylake",
    "-C",
    "link-arg=-fuse-ld=lld",
    "-Z",
    "share-generics=y",
]
